name: Sync Template Updates from BRAN Org

on:
  repository_dispatch:
    types: [template_updated] # Disparado instantaneamente ao fazer merge na main do template
  schedule:
    - cron: '0 0 * * 1' # Executa semanalmente (Toda segunda-feira)
  workflow_dispatch: # Permite disparo manual pelo painel do GitHub Actions

jobs:
  repo-sync:
    name: Sync Downstream Repo with BRAN Template
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Actions Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: BRAN-Org/bran-web-database-template
          upstream_branch: main
          pr_title: "chore(sync): 🚀 Atualizações automáticas do BRAN Web Database Template"
          pr_commit_msg: "chore(sync): mesclar novidades do template central BRAN Org"
          pr_reviewers: "GabrielBaiano"
